#build hacks
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_PREBUILT_ELF_FILES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true

# TWRP Configuration
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"

#maintainer
BOARD_MAINTAINER_NAME := Chongkessob
TW_DEVICE_VERSION := X6532

# Tools
TW_INCLUDE_FB2PNG := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_RESETPROP_SOURCE := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_LIBRESETPROP_SOURCE := true

# TWRP Configs
TW_DEFAULT_BRIGHTNESS := 2047
TW_MAX_BRIGHTNESS := 4095
TW_EXCLUDE_APEX := true
TW_EXCLUDE_LPDUMP := true
TW_EXTRA_LANGUAGES := true
TW_FRAMERATE := 90
TW_THEME := portrait_hdpi
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
TARGET_USES_MKE2FS := true
TW_STATUS_ICONS_ALIGN := center
TW_NO_CPU_TEMP := true
TW_Y_OFFSET := 100
TW_H_OFFSET := -100

BOARD_HAS_NO_REAL_SDCARD := true
BOARD_USES_METADATA_PARTITION := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_NO_SCREEN_TIMEOUT := true
TW_NO_HAPTICS := true
TW_USE_TOOLBOX := true
TW_NO_USB_STORAGE := true
TW_EXCLUDE_APEX := true
TW_HAS_NO_RECOVERY_PARTITION := true
TW_SKIP_COMPATIBILITY_CHECK := true

# Flashing support for system, system_ext, product, and vendor
TW_INCLUDE_REPACKTOOLS := true
TW_USE_SAR_DETECT := true
TW_DYNAMIC_PARTITIONS := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
TW_SUPPORT_INPUT_AIDL := true
TW_SUPPORT_INPUT_HAPTICS := true
